stages:
  - build
  - test
  - deploy
  - destroy

variables:
  VM_IP: "51.124.189.117"
  VM_USER: "mj"
  SSH_PORT: 22

build-job:
  stage: build
  image: gradle:jdk21
  script:
    - ./gradlew build
  only:
    - development
    - main

unit-test-job:
  stage: test
  image: gradle:jdk21
  script:
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: builds/test-results/test/*.xml
  when: manual
  only:
    - development
    - main

deploy-job:
  stage: deploy
  image: almalinux:latest
  before_script:
    - dnf install -y openssh openssh-clients
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -p $SSH_PORT $VM_IP >> ~/.ssh/known_hosts
  script:
    - ssh -p $SSH_PORT $VM_USER@$VM_IP "
        cd ~/biketrust &&
        git reset --hard &&
        git checkout development &&
        git pull origin development &&
        bash scripts/deploy.sh"
  only:
    - development
    - main

destroy-job:
  stage: destroy
  image: almalinux:latest
  before_script:
    - dnf install -y openssh openssh-clients
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -p $SSH_PORT $VM_IP >> ~/.ssh/known_hosts
  script:
    - ssh -p $SSH_PORT $VM_USER@$VM_IP "
        cd ~/biketrust &&
        bash scripts/destroy.sh"
  only:
    - development
    - main
