stages:
  - create_vm
  - test
  - deploy
  - destroy

variables:
  AZURE_REGION: "westeurope"
  VM_ZONE: "2"
  TF_VAR_region: "westeurope"
  PROJECT_REPO: "https://oauth2:${SWIFT_BY_TOKEN}@gitlab.com/kdg-ti/integration-4/2024-2025/team-8/biketrust.git"
  INFRA_REPO: "https://oauth2:${INFRA_REPO_TOKEN}@gitlab.com/kdg-ti/integration-4/2024-2025/team-8/infrastructureautomation.git"
 
create-vm:
  stage: create_vm
  image: alpine:3.18
  before_script:
    - apk add --no-cache bash curl jq git openssh
    - curl -fsSL https://get.opentofu.org/install.sh | bash
    - ln -s $HOME/.opentofu/bin/tofu /usr/local/bin/tofu
    - echo "$AZURE_CREDENTIALS_B64" | base64 -d > creds.json
    - export ARM_CLIENT_ID=$(jq -r .clientId creds.json)
    - export ARM_CLIENT_SECRET=$(jq -r .clientSecret creds.json)
    - export ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId creds.json)
    - export ARM_TENANT_ID=$(jq -r .tenantId creds.json)
  script:
    - git clone "$INFRA_REPO"
    - cd infrastructureautomation/IntegrationInfraSetup/terraform/test-vm
    - tofu init
    - tofu apply -auto-approve
    - echo "VM_IP=$(tofu output -raw vm_public_ip)" >> $CI_PROJECT_DIR/deployment.env
    - echo "VM_USERNAME=$(tofu output -raw vm_username)" >> $CI_PROJECT_DIR/deployment.env
  artifacts:
    reports:
      dotenv: deployment.env


test:
  stage: test
  image: gradle:jdk21
  dependencies:
    - create-vm
  script:
    - source deployment.env
    - echo "$SSH_PRIVATE_KEY" > id_rsa && chmod 600 id_rsa
    - ssh-keyscan $VM_IP >> ~/.ssh/known_hosts
    - |
      ssh -i id_rsa $VM_USERNAME@$VM_IP <<EOF
        git clone $PROJECT_REPO &&
        cd biketrust &&
        ./gradlew test
       EOF
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
  allow_failure: false
  only:
    - development
  

destroy:
  stage: destroy
  image: hashicorp/terraform:light
  dependencies:
    - create-vm
  before_script:
    - apk add bash curl jq openssh git
    - echo "$AZURE_CREDENTIALS_B64" > creds.json
    - export ARM_CLIENT_ID=$(jq -r .clientId creds.json)
    - export ARM_CLIENT_SECRET=$(jq -r .clientSecret creds.json)
    - export ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId creds.json)
    - export ARM_TENANT_ID=$(jq -r .tenantId creds.json)
  script:
    - git clone "$INFRA_REPO"
    - cd infrastructureautomation/IntegrationInfraSetup/terraform/test-vm
    - tofu destroy -auto-approve || echo "already destroyed"
  only:
    - development
  when: always