services:
  db:
    image: postgres:17.2-alpine
    restart: always
    environment:
      POSTGRES_DB: swift_by_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5435:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    restart: on-failure
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      API_KEY: 9f3b570c-1185-471c-b901-a9ae735a27c3
      API_LINK: https://testbench.raoul.dev/api/test
      EMAIL_API: 1cc818ab-3dff-4089-bcfe-634d2f455015
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/swift_by_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: dev

volumes:
  db-data:
