services:
  app:
    build: .
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      API_KEY: 9f3b570c-1185-471c-b901-a9ae735a27c3
      API_LINK: https://testbench.raoul.dev/api/test
      EMAIL_API: 1cc818ab-3dff-4089-bcfe-634d2f455015
      SPRING_PROFILES_ACTIVE: dev

  70a2466 (development)