#spring.datasource.url=jdbc:postgresql://localhost:5435/swift_by_db
#spring.datasource.username=admin
#spring.datasource.password=admin
spring.datasource.url=jdbc:sqlserver://swiftby.database.windows.net:1433;database=swiftdb;user=swiftby@swiftby;password=prrprrtaylorswiftcameby21!;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true