spring.application.name=SwiftBy
# set to 8080 because of Mj
server.port=8080
spring.profiles.active=dev
logging.level."org.hibernate.SQL"=DEBUG
logging.level."org.hibernate.type.descriptor.sql.BasicBinder"=TRACE
spring.jpa.open-in-view=false
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.be.kdg.swiftby=DEBUG

testbenchapi.key=${API_KEY}
testbenchapi.link=${API_LINK}

# email name
email=mohamed-jan.jalloh@student.kdg.be



spring.messages.basename=messages

