
// MOTORS

### get all motors - 200
GET http://localhost:8080/api/motors
Accept: application/json


### get one existing motor - 200
GET http://localhost:8080/api/motors/1
Accept: application/json


### get one non-existing motor - 404
GET http://localhost:8080/api/motors/0
Accept: application/json


### save a motor - 200
POST http://localhost:8080/api/motors
Content-Type: application/json

{
  "engineType": "Bosch CX",
  "gearType": "Automatic",
  "maxPower": 500,
  "nominalPower": 250,
  "torque": 85
}


### delete existing motor - 204
DELETE http://localhost:8080/api/motors/1
Accept: application/json


### delete non-existing motor - 404
DELETE http://localhost:8080/api/motors/0
Accept: application/json
